### ISSUE TITLE
php extension

### ISSUE THREAD

**Issue by jajouka79** [kissit/php-clamav-scan#1]
does this need a php extension? like an .so file?

**Comment by kissit** [comment]
Only requirement is the standard PHP sockets extension which is usually installed by default or at least available via your distro's package manager if not included.  Nothing special is needed for Clamd other than having it running with the socket file enabled in clamd.conf.

**Comment by jajouka79** [comment]
thanks, where should clamd.conf be?

**Comment by kissit** [comment]
clamd.conf is the configuration file for ClamAV, I assume you have that installed.  I know in RHEL/CentOS its located at /etc/clamd.conf.  Otherwise, not sure you would need to check the documentation: https://www.clamav.net/documents/installing-clamav
