### ISSUE TITLE
occur error socket_connect(): unable to connect [13]: Permission denied?

### ISSUE THREAD

**Issue by daitranthanhhoa** [kissit/php-clamav-scan#11]
i had install clamav on centos 7 by url: https://www.hostinger.com/tutorials/how-to-install-clamav-centos7

i had setting:
`
sudo setsebool -P daemons_enable_cluster_mode 1`
and had add user apache to clamscan group
`sudo usermod -a -G clamscan apache`

I change of socket file: 
`private $clamd_sock = "/var/run/clamd.scan/clamd.sock";`
But it occur error:

> socket_connect(): unable to connect [13]: Permission denied

**Comment by marcoczen** [comment]
Hi ...did u ever solve this ?

**Comment by daitranthanhhoa** [comment]
my answer at: https://stackoverflow.com/questions/57855237/clamav-occur-error-socket-connect-unable-to-connect-13-permission-denied

**Comment by kissit** [comment]
Sorry I missed this and glad you got it working!
