### ISSUE TITLE
permission denied to read file

### ISSUE THREAD

**Issue by Conver** [kissit/php-clamav-scan#13]
Hey, thanks for great code.

I'm stock at trying to scan a file, i'm using your test script to test, but I can't seem to figure out which permissions I need to set for the upload folder I need to scan for virus.

I don't use the tmp folder, I use another folder which is used by my app for uploads. I can fine create the 2 test files (bad and good file), but I can't get the script to read the file after it's been created by PHP. What permissions do I need to set? which user/group needs to have permissions?

Thanks,

OS: Ubuntu 20.04
PHP: v7

/note: I can fine scan the files when doing from CLI, so I would guess that clamav has permissions to read the file, however the script doesn't. Is it because it done thru the socket?

**Comment by Conver** [comment]
@kissit - Can you assets me on this matter?

**Comment by kissit** [comment]
@Conver - Can you provide the detailed error messages from PHP when you try to scan?  Generally speaking, yes, the user that is running your PHP code will need to be able to access the ClamAV socket.

> /note: I can fine scan the files when doing from CLI, so I would guess that clamav has permissions to read the file, however the script doesn't. Is it because it done thru the socket?

When you say "when doing from CLI", do you mean a PHP CLI script or using clamscan?  If its working with PHP at that level then yes, definitely seems like the application user needs to be able to access the socket.  What that user is will depend on your configuration.

**Comment by kissit** [comment]
Also check for something like this (forget the name of SELinux in Ubuntu): https://github.com/kissit/php-clamav-scan/issues/11

**Comment by Conver** [comment]
Thanks for reply @kissit 👍 

The error PHP is generating when trying to run the test script is:
````
Testing using the local socket option... Testing a good file... BOO, file is a virus. Message: Permission denied. ERROR Testing a bad file... BOO, file is a virus. Message: Permission denied. ERROR
````
There is no errors or anything in apache nor PHP log, since the script doesn't fail, but the SCAN command returns the permissions denied.


PHP and Apache2 can fine touch the files and read them, just not when trying with the script.

By CLI I meant clamscan yes :)

I have tried that in #11, doesn't help sadly.

Let me know if there is anything else you need to know :)

**Comment by kissit** [comment]
Clamscan doesn't necessarily use clamd by default, so you may not be getting a valid test like that.

Simply put, to things need permissions, it will be different depending on your system so you'll have to adjust accordingly;

- PHP/apache user needs permission to the clamd socket file.
- The user clamd is running as needs access to read the files you scan.

What are the permissions being set for the files by Apache/PHP?

**Comment by Conver** [comment]
-rw-rw-rw-+ 1 www-data www-data 68 Oct 23 17:46 clamav_test.txt

PHP/Apache has access to the socket, else it wouldn't be able to return that error, Correct me if I'm wrong :)

I've giving clamav read access to the files and folder, but should it be clamd? clamav is also added to www-data (apache2) group.

**Comment by kissit** [comment]
It really shouldn't matter if the permissions are -rw-rw-rw-, everyone should be able to read it.  I'm honestly not sure what to say as I've never worked with Clamav on Ubuntu.  I'd try `clamdscan` like here to see if that fails also.  Then also check for Apparmor blocking it.

**Comment by Conver** [comment]
Okay, Will try the clamdscan instead and report back :)

**Comment by julian70400** [comment]
```
                        require 'clamav.php';
                        $clamav = new Clamav();
                        $source_file = $_FILES['myFilel']['tmp_name'];
                        **chmod($source_file, 0644);**
```

!is what I do to avoid this problem.

**Comment by Conver** [comment]
@julian70400 thanks for reply, but **chmod($source_file, 0644);** doesn't work either for some reason. Maybe because I don't use the tmp folder to scan, but I first scan when the file is in the upload folder?

**Comment by Conver** [comment]
Or maybe I need to use **chmod($source_file, 0644);** when the code moves the file to the folder.
