### ISSUE TITLE
clamd.sock file not found

### ISSUE THREAD

**Issue by dnyaneshwarkothule** [kissit/php-clamav-scan#16]
Hi,

I am trying to implement this library but I am not able to locate **clamd.sock** file inside path **_/var/run/clamav/_**.
I have also checked the clamd.conf file and able to locate **LocalSocket** as **/var/run/clamav/clamd.ctl** so I have tried with **clamd.ctl** in the **Clamav.php** file but getting issue as UNKNOWN COMMAND after scanning for test file.

I have also tried changing of **LocalSocket** as **/var/run/clamav/clamd.sock** but its not creating this file and getting **file is missing** error.

Can you please help me with this?

Thank you.

**Comment by kissit** [comment]
Well, this is more of a problem with configuring Clamd than is related to this code, but what happens if you test the LocalSocket from the CLI  like so?  Obviously change the socket file in the command to whatever you have it currently set as.

`$ echo PING | nc -U /var/run/clamav/clamd.sock`

**Comment by devanghire** [comment]
i Have an issue in codeigniter 3 

socket_connect(): unable to connect [10050]: A socket operation encountered a dead network.

please help me for that
