### ISSUE TITLE
Put this code in xampp and the operating system is windows 10

### ISSUE THREAD

**Issue by sandip-divii** [kissit/php-clamav-scan#17]
Set 
$test_dir = 'C:\xampp\htdocs\test\scan\php-clamav-scan-master';

Output:
Testing using the local socket option... Testing a good file...
Fatal error: Uncaught Error: Call to undefined function socket_create() in C:\xampp\htdocs\test\scan\php-clamav-scan-master\Clamav.php:66 Stack trace: #0 C:\xampp\htdocs\test\scan\php-clamav-scan-master\Clamav.php(148): Clamav->socket() #1 C:\xampp\htdocs\test\scan\php-clamav-scan-master\Clamav.php(91): Clamav->send('SCAN C:\\xampp\\h...') #2 C:\xampp\htdocs\test\scan\php-clamav-scan-master\test.php(17): Clamav->scan('C:\\xampp\\htdocs...') #3 {main} thrown in C:\xampp\htdocs\test\scan\php-clamav-scan-master\Clamav.php on line 66

Please help, how to execute this program

**Comment by kissit** [comment]
You need to enable the PHP sockets extension.  How to do that in xampp I have no clue, seems like a common problem though: https://www.google.com/search?q=xampp+Call+to+undefined+function+socket_create.

**Comment by sandip-divii** [comment]
Thank you for your reply. 
But still after enabling the extension I am facing the problem with the path. 
private $clamd_sock = "/var/run/clamav/clamd.sock";
I am using windows 10. What should be the link for clamd.sock? As because I can't find the file.  Or how should I create this file if it is required to create.

Please guide. I shall be grateful to your kind reply.

**Comment by ikunyemingor** [comment]
For Windows 10, you must use the network socket option ```php $clamav = new Clamav(['clamd_ip' => '127.0.0.1']); ```
