### ISSUE TITLE
socket_connect(): unable to connect [10050]: A socket operation encountered a dead network. ( # codeigniter 3)

### ISSUE THREAD

**Issue by devanghire** [kissit/php-clamav-scan#19]
i Have an issue in codeigniter 3 in  (windows 10 )

A PHP Error was encountered
Severity: Warning

Message: socket_connect(): unable to connect [10050]: A socket operation encountered a dead network.

Filename: libraries/Clamav.php

Line Number: 69

please help me for that

**Comment by kissit** [comment]
That sounds like a networking error.  Are you using a socket file or IP/port to connect to clamd?  If the latter, I'd say check your firewall settings.  I don't really support Windows systems so my ability to say what the problem may be is limited.

**Comment by rubenbenjamin** [comment]
For *nix users. 
After I found this
```
 ls -la /var/run/clamav/clamd.ctl
srw-rw-rw- 1 clamav clamav 0 May 20 15:54 /var/run/clamav/clamd.ctl
```


Changing  Clamav.php
from
`private $clamd_sock = "/var/run/clamav/clamd.sock";`
To
`private $clamd_sock = "/var/run/clamav/clamd.ctl";`
Did the trick for me
