### ISSUE TITLE
Cannot find socket file

### ISSUE THREAD

**Issue by mihitha** [kissit/php-clamav-scan#2]
I am getting,

`Warning: socket_connect(): unable to connect [2]: No such file or directory in clamav.php on line 48`

How can I find default socket path for ClamAV?

Environment - Ubuntu 16.04/PHP7/NGINX

**Comment by kissit** [comment]
Assuming you've installed ClamAV/Clamd, in the clamd.conf file (/etc/clamd.conf ) look for this option:

```
# Path to a local socket file the daemon will listen on.
# Default: disabled (must be specified by a user)
LocalSocket /var/run/clamav/clamd.sock
```

It may be commented out by default.  Uncomment it and specify the path, then restart clamd.  Or if it is already enabled use the path that's set when you instantiate the PHP lib.

**Comment by mihitha** [comment]
Thanks for the reply. I figured that out, it was the default socket name. I changed it to "/var/run/clamav/clamd.ctl" and worked. Not too sure why and how that socket name got changed from "clamd.sock" to "clamd.ctl".
