### ISSUE TITLE
Add support for scanning of files over a network

### ISSUE THREAD

**Issue by kissit** [kissit/php-clamav-scan#5]
Currently this requires that Clamd be running on the same host as the files.  One day I want to add the ability to stream file data over the network and perform the scan on a different host.

See the INSTREAM option here: https://linux.die.net/man/8/clamd

**Comment by rvstaveren** [comment]
The following piece of code will accomplish this. It might be worthwhile to replace the scan method with this, as it also allows a local clamd to reach files in (systemd) sandboxes

public function scanstream($file) {
       $socket = $this->socket();
       if(!$socket)
           return false;
       if(file_exists($file)) {
           if ($scan_fh = fopen($file, 'rb')) {
               $chunksize = filesize($file) < 8192 ? filesize($file) : 8192;
               $command = "zINSTREAM\0";
               socket_send($socket, $command, strlen($command), 0);
               while (!feof($scan_fh)) {
                   $data =  fread($scan_fh, $chunksize);
                   $packet = pack(sprintf("Na%d",$chunksize),$chunksize, $data);
                   socket_send($socket, $packet, $chunksize+4, 0);
               }
               socket_send($socket, pack("Nx",0), 5, 0);
               socket_recv($socket, $scan, $this->clamd_sock_len, 0);
               socket_close($socket);
               trim($scan);
               $scan = substr(strrchr($scan, ":"), 1);
               if($scan !== false) {
                   $this->message = trim($scan);
                   if($this->message == "OK") {
                       return true;
                   }
               } else {
                   $this->message = "Scan failed";
               }
           }
       } else {
           $this->message = "File not found";
       }
       return false;
   }

**Comment by vicdev82** [comment]
Why are you adding +4 to chunksize in 
> socket_send($socket, $packet, $chunksize+4, 0);

**Comment by rvstaveren** [comment]
I wrote this two years ago and haven't used it anymore. therefor I can't reliably explain the +4 which should have been a self describing named constant instead. It probably accounts for the RLE encoding that is used in the INSTREAM format.
The issue of clamd not being able to scan local files outside of its systemd sandbox probably remains, unless one has disabled it
