### ISSUE TITLE
Some improvements :)

### ISSUE THREAD

**Issue by Trolli07** [kissit/php-clamav-scan#6]
Hello,

I found a few little improvements to do :
- There's a var_dump
- `return $ping == 'PONG';` is better
- the code doesn't seem to meet PHP Coding Standards

**Comment by kissit** [comment]
> There's a var_dump

Thanks, I've removed.

> return $ping == 'PONG'; is better

Maybe for you it us, but returning true/false is easier for my use case as I can then do a simple check like so without having to check the string each time:
`if($clamav->ping())`

> the code doesn't seem to meet PHP Coding Standards

It meets my coding standards :-)  You may choose to follow PSR-whatever but I do not.
