### ISSUE TITLE
Warning:  socket_connect(): unable to connect [13]: Permission denied

### ISSUE THREAD

**Issue by lfolco** [kissit/php-clamav-scan#9]
Are there any sort of permission changes I need to make to get this working? I know you can change the user and group in `/etc/clamd.conf`; is that required?

**Comment by kissit** [comment]
I've never had to change anything related to permissions on the socket.  I know the error says permission denied which leads me to believe you have the socket file enabled, but in case its an erroneous message do you have your socket enabled in /etc/clamd.conf and using the same path to the socket in your code?

In /etc/clamd.conf
```
# Path to a local socket file the daemon will listen on.
# Default: disabled (must be specified by a user)
LocalSocket /var/run/clamav/clamd.sock
```

In your code (if your socket file is not at /var/run/clamav/clamd.sock).
```
$clamav = new Clamav(array('clamd_sock' => '/path/to/clamd.sock'));
```

For reference, here's the permissions on my socket file, and web server is running as www user with no issues connecting.
```
# ls -l /var/run/clamav/clamd.sock
srw-rw-rw-  1 clamav  clamav  0 Mar 13 20:09 /var/run/clamav/clamd.sock
```

**Comment by lfolco** [comment]
Is your `www` user a member of the `clamav` group?

**Comment by kissit** [comment]
No, it isn't.  What OS are you using?  I just had a thought that possibly SELinux could be blocking access to it if you are on RHEL/CentOS and have it enabled.  Any cases where I've used CentOS with this SELinux was disabled.

**Comment by lfolco** [comment]
That was it! But, now running into a different issue: `clamav_test.txt: lstat() failed: Permission denied. ERROR`

**Comment by kissit** [comment]
This looks like a problem with Clamav/clamd not having permissions to the files you're trying to scan, not with this lib.  Not sure if you completely disabled SELinux or not, but if you didn't and just adjusted rules for the last problem it could be SELinux related.  

Something here may help also: https://www.google.com/search?q=clamav%20lstat()%20failed%3A%20Permission%20denied
